// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWcHnbxd8w6jl2AizxM407y08e1IxJDk',
    appId: '1:226067524041:web:7a9b1b42cc24085c576018',
    messagingSenderId: '226067524041',
    projectId: 'authentication-7acb1',
    authDomain: 'authentication-7acb1.firebaseapp.com',
    storageBucket: 'authentication-7acb1.firebasestorage.app',
    measurementId: 'G-YT5341G5SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfUH3mftOBCq-7f506q5xFSVEZQjRAY-s',
    appId: '1:226067524041:android:f4d9695c7e6d5264576018',
    messagingSenderId: '226067524041',
    projectId: 'authentication-7acb1',
    storageBucket: 'authentication-7acb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ihBg518r4uiwRUwX2GVdls3c8Qw8rys',
    appId: '1:226067524041:ios:a810047e1e4f956c576018',
    messagingSenderId: '226067524041',
    projectId: 'authentication-7acb1',
    storageBucket: 'authentication-7acb1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ihBg518r4uiwRUwX2GVdls3c8Qw8rys',
    appId: '1:226067524041:ios:a810047e1e4f956c576018',
    messagingSenderId: '226067524041',
    projectId: 'authentication-7acb1',
    storageBucket: 'authentication-7acb1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDWcHnbxd8w6jl2AizxM407y08e1IxJDk',
    appId: '1:226067524041:web:9ea386df09973bd8576018',
    messagingSenderId: '226067524041',
    projectId: 'authentication-7acb1',
    authDomain: 'authentication-7acb1.firebaseapp.com',
    storageBucket: 'authentication-7acb1.firebasestorage.app',
    measurementId: 'G-MQRRVMV24D',
  );
}
